version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/contracts"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/dev-frontend"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/examples"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/fuzzer"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/lib-base"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/lib-ethers"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/lib-react"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/lib-subgraph"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/providers"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/packages/subgraph"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
